### ISSUE TITLE
UnboundLocalError: local variable 'background_cmd' referenced before assignment

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#108]
merida1 failed with the following error on 2021/12/05:

```
BBS> ==============================================================
BBS>   (Re)make BBS_CENTRAL_BASEURL/products-in/merida1/... OK
BBS> [STAGE2] STARTING STAGE2 at Sun Dec  5 15:00:09 2021
BBS>   (Re)make BBS_CENTRAL_BASEURL/products-in/merida1/install/... OK
BBS>   Syncing local '/Users/biocbuild/bbs-3.15-bioc/meat' with BBS_MEAT0_RDIR
BBS>   runJob(): /usr/bin/rsync -rl --delete --exclude='.svn' --exclude='.git' --exclude='.github' --exclude='.git_*' --rsh 'ssh -F /Users/biocbuild/.ssh/config' -rlptz biocbuild@nebbiolo1:/home/biocbuild/bbs-3.15-bioc/MEAT0/ .
BBS>     pid = 11632 / time [] = 15.88 seconds / retcode = 0 / OK
BBS> [STAGE2] cd BBS_WORK_TOPDIR/gitlog
BBS>   Syncing local '/Users/biocbuild/bbs-3.15-bioc/gitlog' with BBS_GITLOG_RDIR
BBS>   runJob(): /usr/bin/rsync -rl --delete --exclude='.svn' --exclude='.git' --exclude='.github' --exclude='.git_*' --rsh 'ssh -F /Users/biocbuild/.ssh/config' -rlptz biocbuild@nebbiolo1:/home/biocbuild/public_html/BBS/3.15/bioc/gitlog/ .
BBS>     pid = 11640 / time [] = 2.30 seconds / retcode = 0 / OK
BBS> [STAGE2] cd BBS_WORK_TOPDIR/STAGE2_tmp
BBS> [STAGE2] Update non-target packages (1st run) ... OK
BBS> [build_pkg_dep_graph] 2059 pkgs written to target_pkgs.txt
BBS> [build_pkg_dep_graph] Calling build_pkg_dep_graph() defined in /Users/biocbuild/BBS/utils/build_pkg_dep_graph.R to generate file pkg_dep_graph.txt ... OK
BBS>   Putting pkg_dep_graph.txt in BBS_CENTRAL_BASEURL/products-in/merida1/:
BBS>   runJob(): /usr/bin/rsync -rl --delete --exclude='.svn' --exclude='.git' --exclude='.github' --exclude='.git_*' --rsh 'ssh -F /Users/biocbuild/.ssh/config' pkg_dep_graph.txt biocbuild@nebbiolo1:/home/biocbuild/public_html/BBS/3.15/bioc/products-in/merida1
BBS>     pid = 14624 / time [] = 1.66 seconds / retcode = 0 / OK
BBS> [build_pkg_dep_graph] Loading pkg_dep_graph.txt file ... OK (4080 pkgs and their deps loaded)
BBS> [build_pkg_dep_graph] DONE.
BBS> [get_installed_pkgs] 4115 installed pkgs
BBS> [STAGE2] cd BBS_MEAT_PATH
BBS> [STAGE2] Injecting fields into DESCRIPTION
BBS> [STAGE2] Re-install supporting packages
BBS> Preparing STAGE2 job queue ... OK
BBS> Job summary:
BBS> | 0 (out of 2059) target pkgs are not supporting pkgs
BBS> |   => no need to install them
BBS> |   => they're not going in the installation queue
BBS> | 4080 pkgs in the installation queue (all supporting pkgs):
BBS> |   o 2059 are target pkgs
BBS> |       => will (re-)install them with 'R CMD INSTALL'
BBS> |   o 2021 are non-target pkgs:
BBS> |     - 2019 are already installed
BBS> |         => won't re-install them (job will be skipped)
BBS> |     - 2 are not already installed
BBS> |         => will install them with
BBS> |              install.packages(pkg, repos=non_target_repos,
BBS> |                               dep=FALSE, ...)
BBS> | Total nb of packages to install: 2061
BBS>
BBS> BEGIN STAGE2 loop.
Traceback (most recent call last):
  File "/Users/biocbuild/BBS/BBS-run.py", line 739, in <module>
    STAGE2()
  File "/Users/biocbuild/BBS/BBS-run.py", line 454, in STAGE2
    STAGE2_loop(job_queue, BBSvars.install_nb_cpu, out_dir)
  File "/Users/biocbuild/BBS/BBS-run.py", line 360, in STAGE2_loop
    background_cmd, background_output,
UnboundLocalError: local variable 'background_cmd' referenced before assignment
```

**Comment by hpages** [comment]
Hi Jennifer,

My fault. I've been making some changes to experiment with asynchronous transmission of the build products. Still working on it. Hopefully I'll have something that works before the end of the day.

Thanks for keeping an eye on the builds.

H.

**Comment by hpages** [comment]
Asynchronous transmission of build products is now implemented and is only activated on merida1 for the moment. If every goes fine, I'll activate on riesling1 in the next couple of days.

The way it works is that build products are stored in a local buffer (`~biocbuild/bbs-3.15-bioc/products-out/`) on merida1 instead of being immediately sent to the central builder. Then every once in a while `~biocbuild/public_html/BBS/3.15/bioc/products-in/` on the central builder gets resynced with `~biocbuild/bbs-3.15-bioc/products-out/`. With the visible effect that build products now arrive in batches on the central builder instead of arriving individually.

H.
