### ISSUE TITLE
BBS error when build nodes haven't finished

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#18]
When a build node (e.g. perceval) hasn't completed, the postrun.sh script and presumably BBS-make-OUTGOING.py (components in BBS) will fail.  Alternative approaches might be : 
- Not starting postrun if all nodes haven't finished (determine this dynamically, not manually)
- Handling the case that a node hasn't finished and carrying on successfully 

```
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/DiffLogo_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/DNABarcodes_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/EnrichedHeatmap_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/FindMyFriends_1.0.2.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/Guitar_1.7.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/DAPAR_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/gcatest_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/iCheck_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/Imetagene_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/lfa_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/MEAL_1.0.1.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/metagenomeFeatures_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/pathVar_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/Prostar_1.0.1.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/SISPA_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/SWATH2stats_1.0.1.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/GUIDEseq_1.0.4.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/DChIPRep_1.0.3.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/GeneBreak_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/RiboProfiling_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/SNPhood_1.0.1.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/miRcomp_1.0.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/biobroom_1.2.0.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/subSeq_1.0.1.zip to OUTGOING folder...
BBS> [stage6]   - copying /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin/CNPBayes_1.0.0.zip to OUTGOING folder...
BBS> [stage6] END copying outgoing packages from /home/biocbuild/public_html/BBS/3.2/bioc/nodes/moscato1/buildbin.
BBS> [stage6] mkdir /home/biocbuild/public_html/BBS/3.2/bioc/OUTGOING/mac.binary
BBS> [stage6] cd /home/biocbuild/public_html/BBS/3.2/bioc/OUTGOING/mac.binary/
BBS> [stage6] BEGIN copying outgoing packages from /home/biocbuild/public_html/BBS/3.2/bioc/nodes/perceval/buildbin.
Traceback (most recent call last):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 210, in <module>
    stage6_make_OUTGOING()
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 193, in stage6_make_OUTGOING
    copy_outgoing_pkgs(tmp[1], source_node)
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 72, in copy_outgoing_pkgs
    if pkgMustBeRejected(node_hostname, node_id, pkg):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 48, in pkgMustBeRejected
    dcf = open(summary_file, 'r')
IOError: [Errno 2] No such file or directory: '/home/biocbuild/public_html/BBS/3.2/bioc/nodes/perceval/buildbin/Biobase.buildbin-summary.dcf'

```

**Comment by b-long** [comment]
Anyone interested in working this issue, you might consider writing some Python early in "_postrun.sh_" that looks for the `EndOfRun.txt` file.  If the file is missing, use Python to send an email to notify the core team.

The following may be useful in approaching this : 
- https://github.com/Bioconductor/BBS/blob/master/BBS-notify.py 
- https://github.com/Bioconductor/BBS/blob/master/bbs/email.py
