### ISSUE TITLE
'morelia' build node not available

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BBS#30]
```
[mtmorgan@juanite ~]$ ping morelia
PING morelia.fhcrc.org (140.107.170.55) 56(84) bytes of data.

--- morelia.fhcrc.org ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 999ms
```

and (there are several of these, since Nov 25):

```
biocbuild@zin2:~$ grep -A10 -B2 Trace /home/biocbuild/bbs-3.3-bioc/log/zin2.log
BBS> [stage6] cd /home/biocbuild/public_html/BBS/3.3/bioc/OUTGOING/mac.binary.mavericks/
BBS> [stage6] BEGIN copying outgoing packages from /home/biocbuild/public_html/BBS/3.3/bioc/nodes/morelia/buildbin.
Traceback (most recent call last):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 209, in <module>
    stage6_make_OUTGOING()
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 192, in stage6_make_OUTGOING
    copy_outgoing_pkgs(tmp[1], source_node)
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 72, in copy_outgoing_pkgs
    if pkgMustBeRejected(node_hostname, node_id, pkg):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 30, in pkgMustBeRejected
    dcf = open(summary_file, 'r')
IOError: [Errno 2] No such file or directory: '/home/biocbuild/public_html/BBS/3.3/bioc/nodes/morelia/buildsrc/Biobase.buildsrc-summary.dcf'
```

I think a work-around is to remove the build node from the build system? Obviously the problem with the build node needs to be investigated.

**Comment by b-long** [comment]
I've removed morelia from (at least) the `postrun.sh` phase.  I'm not sure if this impacts other phases of the build, but it's the same process we've done in the past when `perceval` has been in a bad state: 
```
root@zin2:/home/biocbuild/BBS/3.3/bioc/zin2# pwd && git diff config.sh
/home/biocbuild/BBS/3.3/bioc/zin2
diff --git a/3.3/bioc/zin2/config.sh b/3.3/bioc/zin2/config.sh
index 71a9bd6..eca2f53 100644
--- a/3.3/bioc/zin2/config.sh
+++ b/3.3/bioc/zin2/config.sh
@@ -49,7 +49,7 @@ cd "$wd0"
 # packages to propagate and to later not be replaced by the bi-arch when
 # the dropped node is back.
 
-export BBS_OUTGOING_MAP="source:zin2/buildsrc win.binary:moscato2/buildbin mac.binary.mavericks:morelia/buildbin"
+export BBS_OUTGOING_MAP="source:zin2/buildsrc win.binary:moscato2/buildbin"
 
 # Needed only on the node performing stage7a (BBS-make-STATUS_DB.py) and
 # stage8 (BBS-report.py)
@@ -57,7 +57,7 @@ export BBS_OUTGOING_MAP="source:zin2/buildsrc win.binary:moscato2/buildbin mac.b
 # IMPORTANT: BBS-report.py will treat BBS_REPORT_PATH as a _local_ path so it
 # must be run on the BBS_CENTRAL_RHOST machine.
 
-export BBS_REPORT_NODES="zin2 moscato2:bin morelia:bin"
+export BBS_REPORT_NODES="zin2 moscato2:bin"
 #export BBS_SVNCHANGELOG_URL="http://fgc.lsi.umich.edu/cgi-bin/blosxom.cgi"
 export BBS_REPORT_PATH="$BBS_CENTRAL_RDIR/report"
 export BBS_REPORT_CSS="$BBS_HOME/$BBS_BIOC_VERSION/report.css"
```
This should allow build reports to be generated for other devel build nodes (moscato2 and zin2).

**Comment by b-long** [comment]
Waiting on feedback from Raphael.

**Comment by b-long** [comment]
Morelia is back.
