### ISSUE TITLE
'PGPC' devel data-experiment package does not propagating

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BBS#31]
The package seems to build successfully on zin2

```
http://bioconductor.org/checkResults/3.3/data-experiment-LATEST/PGPC/zin2-buildsrc.html
```

but it does not propagate

```
$ curl -I http://bioconductor.org/packages/3.3/data/experiment/html/PGPC.html
HTTP/1.1 404 Not Found
```

This is also true for `PCHiCdata`, and the failure to propagate occurred before morelia failed.

**Comment by b-long** [comment]
Currently, the last lines in the file `/home/biocbuild/bbs-3.3-data-experiment/log/zin2.log`, are : 
```
BBS> [stage6] END copying outgoing packages from /home/biocbuild/public_html/BBS/3.3/data-experiment/nodes/moscato2/buildbin.
BBS> [stage6] mkdir /home/biocbuild/public_html/BBS/3.3/data-experiment/OUTGOING/mac.binary
BBS> [stage6] cd /home/biocbuild/public_html/BBS/3.3/data-experiment/OUTGOING/mac.binary/
BBS> [stage6] BEGIN copying outgoing packages from /home/biocbuild/public_html/BBS/3.3/data-experiment/nodes/morelia/buildbin.
Traceback (most recent call last):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 209, in <module>
    stage6_make_OUTGOING()
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 192, in stage6_make_OUTGOING
    copy_outgoing_pkgs(tmp[1], source_node)
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 72, in copy_outgoing_pkgs
    if pkgMustBeRejected(node_hostname, node_id, pkg):
  File "/home/biocbuild/BBS/BBS-make-OUTGOING.py", line 30, in pkgMustBeRejected
    dcf = open(summary_file, 'r')
IOError: [Errno 2] No such file or directory: '/home/biocbuild/public_html/BBS/3.3/data-experiment/nodes/morelia/buildsrc/affydata.buildsrc-summary.dcf'
```
This isn't the root cause, but if _Stage 6_ is exiting early because some package artifacts are missing, perhaps we can modify the code to handle this case.

We've found that the cron jobs to update the website were inadvertently commented out (in devel and release), and so now they're enabled.  We should see this package updated after Wednesday's build (check on Thursday morning).

**Comment by mtmorgan** [comment]
cron jobs reactivated, package propagates.
